# Minimal Prometheus (use kube-prometheus-stack for production)
apiVersion: v1
kind: ConfigMap
metadata: { name: prometheus-config, namespace: learning01 }
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-pods'
        static_configs:
          - targets: ['spring-svc.learning01.svc.cluster.local:8080','vertx-svc.learning01.svc.cluster.local:8080']
