# Build stage
FROM eclipse-temurin:11 as build
WORKDIR /app
COPY pom.xml mvnw ./
COPY src ./src
RUN ./mvnw clean package -DskipTests

# Run stage
FROM eclipse-temurin:11-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar vertx.jar
EXPOSE 8080
CMD ["java", "-jar", "/app/vertx.jar"]
