name: CI Build and Push
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Spring
        run: |
          cd spring-api
          mvn -B -DskipTests package
          docker build -f docker/Dockerfile.spring -t ghcr.io/${{ github.repository_owner }}/spring-api:latest .
          echo "built spring"
      - name: Build Vert.x
        run: |
          cd vertx-service
          mvn -B -DskipTests package
          docker build -f docker/Dockerfile.vertx -t ghcr.io/${{ github.repository_owner }}/vertx-service:latest .
      - name: Build React Image
        run: |
          cd react-app
          npm run build
          cd ..
          docker build -f docker/Dockerfile.react -t ghcr.io/${{ github.repository_owner }}/react-app:latest .
      - name: Push images
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/spring-api:latest
          docker push ghcr.io/${{ github.repository_owner }}/vertx-service:latest
          docker push ghcr.io/${{ github.repository_owner }}/react-app:latest