name: CI Build and Deploy on VM

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./update_and_deploy.sh

      - name: Run deployment script
        run: ./update_and_deploy.sh
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
